routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [RecipeController::class, 'index'])->name('home');

Route::get('/recipe/manage', [RecipeController::class, 'manage'])->name('manage')->middleware('auth');
Route::resource('/recipe', RecipeController::class)->except(['index'])->middleware('auth')->only(['create', 'store', 'show', 'edit', 'update', 'destroy']);

//user authentication
Route::get('/register', [UserController::class, 'create'])->name('register')->middleware('guest');
Route::post('/users', [UserController::class, 'store'])->name('user.store');
Route::get('/login', [UserController::class, 'login'])->name('login')->middleware('guest');
Route::post('/users/authenticate', [UserController::class, 'authenticate'])->name('user.authenticate');
Route::get('/logout', [UserController::class, 'logout'])->name('logout')->middleware('auth');

app/Models/CookingStep.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CookingStep extends Model
{
    use HasFactory;

    protected $fillable = [
      'recipe_id',
      'text'
    ];

    public function recipe(): BelongsTo
    {
        return $this->belongsTo(Recipe::class);
    }
}

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Ingredient extends Model
{
    use HasFactory;

    protected $fillable = [
        'recipe_id',
        'ingredient',
        'amount'
    ];

    public function recipe(): BelongsTo
    {
        return $this->belongsTo(Recipe::class);
    }
}

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Recipe extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'title',
        'meal_type',
        'cooking_time',
        'serving_size',
        'description',
        'image'
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function ingredients():HasMany
    {
        return $this->hasMany(Ingredient::class, 'recipe_id');
    }

    public function cookingSteps():HasMany
    {
        return $this->hasMany(CookingStep::class, 'recipe_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'email',
        'password',
        'image',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function recipes(): HasMany
    {
        return $this->hasMany(Recipe::class, 'user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRecipeRequest;
use App\Models\Recipe;
use App\Repositories\RecipeRepository;
use App\Services\RecipeService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class RecipeController extends Controller
{

    public function __construct(
        private RecipeService $recipeService,
        private RecipeRepository $recipeRepository,
    )
    {}

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $recipes = $this->recipeRepository->getLatestRecipes(9);

        return view('index', [
            'recipes' => $recipes,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('recipes.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRecipeRequest $request): RedirectResponse
    {
        $this->recipeService->store($request);
        return redirect()->route('home')->with('message', 'Recipe created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Recipe $recipe): View
    {
        return view('recipes.show',[
            'recipe' => $recipe
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Recipe $recipe): View
    {
        return view('recipes.edit', [
            'recipe' => $recipe
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(StoreRecipeRequest $request, Recipe $recipe)
    {
        $this->recipeService->update($request, $recipe);
        return redirect()->route('manage')->with('message', 'Recipe updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Recipe $recipe): RedirectResponse
    {
        $this->recipeService->delete($recipe);
        return redirect()->route('manage')->with('message', 'Listing deleted successfully');
    }

    public function manage(): View
    {
        $recipes = $this->recipeRepository->getUserRecipes();

        return view('recipes.manage',[
            'recipes' => $recipes,
        ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreLoginUserRequest;
use App\Http\Requests\StoreRegisterUserRequest;
use App\Services\UserAuthService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class UserController extends Controller
{
    public function __construct(public UserAuthService $userAuthService)
    {}

    public function create(): View
    {
        return view('user.register');
    }

    public function store(StoreRegisterUserRequest $request): RedirectResponse
    {
        $formFields = $request->validated();
        $user = $this->userAuthService->storeUser($formFields);

        auth()->login($user);

        return redirect()->route('home')->with('message', 'User created and logged in');
    }

    public function logout(Request $request): RedirectResponse
    {
        auth()->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('home')->with('message', 'You have been logged out');
    }

    public function login(): View
    {
        return view('user.login');
    }

    public function authenticate(StoreLoginUserRequest $request): RedirectResponse
    {
        $credentials = $request->except('_token');

        try {
            return $this->userAuthService->checkUserCredentials($credentials);
        } catch (ValidationException $e) {
            return back()->withErrors($e->errors())->onlyInput('email');
        }
    }
}

resources/views/index.blade.php
<x-base>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach($recipes as $recipe)
            <div class="col">
                <div class="card tex" style="height: 450px; display: flex; flex-direction: column;">
                    <div class="text-center" style="height: 200px; overflow: hidden;">
                        <img src="{{$recipe->image ? asset('storage/recipes/'. $recipe->image) : asset('/images/no-recipe-image.jpg')}}"
                             class="card-img-top"
                             style="max-height: 100%; object-fit: cover;"
                             alt="Recipe image">
                    </div>
                    <div class="card-body flex-grow-1">
                        <h5 class="card-title">{{$recipe->title}}</h5>
                        <p class="card-text">{{$recipe->description}}</p>
                    </div>
                    <div class="d-flex justify-content-between text-center p-3">
                        <div class="pt-2">
                            <p>Author: {{$recipe->user->username}}</p>
                        </div>
                        <div class="ms-auto">
                            <a href="{{ route('recipe.show', ['recipe' => $recipe->id]) }}" class="btn btn-primary">Check recipe</a>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>

    <div class="d-flex justify-content-end mt-2">
        {!! $recipes->links() !!}
    </div>
</x-base>

resources/views/recipes/create.blade.php
<x-base>
    <h3 class="text-center">Create recipe</h3>
    <div class="offset-3 col-6">

        <form action="{{ route('recipe.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="title" id="title" placeholder="name@example.com" value="{{old('title')}}">
                <label for="title">Title</label>
                @error('title')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <select class="form-select form-select mb-3" name="meal_type" id="meal_type" aria-label="Large select example">
                <option selected>Meal type</option>
                <option value="breakfast">Breakfast</option>
                <option value="launch">Launch</option>
                <option value="dinner">Dinner</option>
                <option value="desert">Desert</option>
            </select>
            @error('meal_type')
                <p class="text-danger">{{$message}}</p>
            @enderror

            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="cooking_time" id="cooking_time" placeholder="name@example.com" value="{{old('cooking_time')}}">
                <label for="cooking_time">Cooking time (minutes)</label>
                @error('cooking_time')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="serving_size" id="serving_size" placeholder="name@example.com" value="{{old('serving_size')}}">
                <label for="serving_size">Serving Size</label>
                @error('serving_size')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-floating mb-3">
                <textarea class="form-control" name="description" id="description" style="height: 100px; resize: none" placeholder="name@example.com">{{old('description')}}</textarea>
                <label for="description">Short description</label>
                @error('description')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="input-group mb-3">
                <input type="file" name="image" class="form-control" id="image">
                <label class="input-group-text" for="image">Upload</label><br>
                @error('image')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div x-data="{ ingredientCounter: 1 }">
                <h4>Ingredients</h4>

                <template x-for="ingredient in ingredientCounter" :key="ingredient">
                    <div class="input-group mb-3">
                        <span class="input-group-text" x-text="ingredient"></span>
                        <input type="text" class="form-control" :name="'ingredient' + ingredient" aria-label="Ingredient" placeholder="Ingredient">
                        <input type="text" class="form-control" :name="'amount' + ingredient" aria-label="Amount" placeholder="Amount">
                    </div>
                </template>
                <button type="button" @click="ingredientCounter++" class="btn btn-primary mb-3">Add Ingredient</button>
            </div>

            <div x-data="{ cookingStepCounter: 1 }">
                <h4>Cooking steps</h4>

                <template x-for="cookingStep in cookingStepCounter" :key="cookingStep">
                    <div class="input-group mb-3">
                        <span class="input-group-text" x-text="cookingStep"></span>
                        <textarea class="form-control" :name="'cookingStep' + cookingStep" aria-label="With textarea"></textarea>
                    </div>
                </template>
                <button type="button" @click="cookingStepCounter++" class="btn btn-primary mb-3">Add cookingStep</button>
            </div>

            <button class="btn btn-primary mb-3">Submit</button>
        </form>

    </div>
</x-base>

resources/views/recipes/edit.blade.php
<x-base>
    <h3 class="text-center">Update recipe</h3>
    <div class="offset-3 col-6">

        <form action="{{ route('recipe.update',['recipe' => $recipe->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="title" id="title" value="{{$recipe->title}}">
                <label for="title">Title</label>
                @error('title')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <select class="form-select form-select mb-3" name="meal_type" id="meal_type" aria-label="Large select example">
                <option value="" disabled>Select Meal Type</option>
                <option value="breakfast" {{ old('meal_type', $recipe->meal_type) === 'breakfast' ? 'selected' : '' }}>Breakfast</option>
                <option value="launch" {{ old('meal_type', $recipe->meal_type) === 'launch' ? 'selected' : '' }}>Launch</option>
                <option value="dinner" {{ old('meal_type', $recipe->meal_type) === 'dinner' ? 'selected' : '' }}>Dinner</option>
                <option value="dessert" {{ old('meal_type', $recipe->meal_type) === 'dessert' ? 'selected' : '' }}>Dessert</option>
            </select>

            @error('meal_type')
            <p class="text-danger">{{$message}}</p>
            @enderror

            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="cooking_time" id="cooking_time" value="{{$recipe->cooking_time}}">
                <label for="cooking_time">Cooking time (minutes)</label>
                @error('cooking_time')
                <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="serving_size" id="serving_size" placeholder="name@example.com" value="{{$recipe->serving_size}}">
                <label for="serving_size">Serving Size</label>
                @error('serving_size')
                <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-floating mb-3">
                <textarea class="form-control" name="description" id="description" style="height: 100px; resize: none" placeholder="name@example.com">{{$recipe->description}}</textarea>
                <label for="description">Short description</label>
                @error('description')
                <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="input-group mb-3">
                <input type="file" name="image" class="form-control" id="image">
                <label class="input-group-text" for="image">Upload</label><br>
            </div>
            <div>
                <img
                    src="{{$recipe->image ? asset('storage/recipes/'. $recipe->image) : asset('/images/no-recipe-image.jpg')}}"
                    style="max-height: 100px; max-width: 100px"
                    alt=""
                />
                @error('image')
                <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <h4>Ingredients</h4>
            <div>
                @foreach($recipe->ingredients as $ingredient)
                    <div class="input-group mb-3">
                        <span class="input-group-text"></span>
                        <input type="hidden" name="ingredients[{{ $ingredient->id }}][id]" value="{{ $ingredient->id }}">
                        <input type="text" class="form-control" name="ingredients[{{ $ingredient->id }}][ingredient]" aria-label="Ingredient" placeholder="Ingredient" value="{{ $ingredient->ingredient }}">
                        <input type="text" class="form-control" name="ingredients[{{ $ingredient->id }}][amount]" aria-label="Amount" placeholder="Amount" value="{{ $ingredient->amount }}">
                    </div>
                @endforeach
            </div>

            <h4>Cooking steps</h4>
            <div>
                @foreach($recipe->cookingSteps as $cookingStep)
                    <div class="input-group mb-3">
                        <span class="input-group-text"></span>
                        <input type="hidden" name="cooking_steps[{{ $cookingStep->id }}][id]" value="{{ $cookingStep->id }}">
                        <textarea class="form-control" name="cooking_steps[{{ $cookingStep->id }}][text]" aria-label="With textarea">{{ $cookingStep->text }}</textarea>
                    </div>
                @endforeach
            </div>

            <button class="btn btn-primary">Update recipe</button>
        </form>
    </div>
</x-base>

resources/views/recipes/manage.blade.php
<x-base>
    <table class="table table-striped">
        <thead class="table-primary">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Meal type</th>
            <th scope="col">Cooking time</th>
            <th scope="col">Serving size</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach($recipes as $recipe)
            <tr>
                <td>{{$recipe->title}}</td>
                <td>{{$recipe->meal_type}}</td>
                <td>{{$recipe->cooking_time}}</td>
                <td>{{$recipe->serving_size}}</td>
                <td class="col-3">
                    <a href="{{ route('recipe.show', ['recipe' => $recipe->id]) }}" class="btn btn-primary">Check recipe</a>
                    <a href="{{route('recipe.edit', ['recipe' => $recipe->id])}}" style="text-decoration: none">
                        <button class="btn btn-info d-inline">Edit</button>
                    </a>
                    <form action="{{route('recipe.destroy', ['recipe' => $recipe->id])}}" method="POST" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</x-base>

resources/views/recipes/show.blade.php
<x-base>
    <div>
        <div class="text-center">
            <img src="{{$recipe->image ? asset('storage/recipes/'. $recipe->image) : asset('/images/no-recipe-image.jpg')}}"
                 style="max-height: 250px; max-width: 250px"  alt="">
            <h2>{{$recipe->title}} </h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Meal</th>
                    <th scope="col">Cooking time</th>
                    <th scope="col">Serving size</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{$recipe->meal_type}}</td>
                    <td>{{$recipe->cooking_time}}</td>
                    <td>{{$recipe->serving_size}}</td>
                </tr>
                </tbody>
            </table>

            <h2>Ingredients</h2>

            <table class="table">
                <thead>
                <tr>
                    <th>Ingredient</th>
                    <th>Amount</th>
                </tr>
                </thead>
                <tbody>
                @foreach($recipe->ingredients as $ingredient)
                    <tr>
                        <td>{{$ingredient->ingredient}}</td>
                        <td>{{$ingredient->amount}}</td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>

        <div class="mt-5">
            <h2>Description:</h2>
            <p>{{$recipe->description}}</p>
        </div>

        <div class="mt-5">
            <h2>Steps:</h2>
            @php
                $stepOrder = 1
            @endphp
            @foreach($recipe->cookingSteps as $cookingStep)
                <div class="row my-4">
                    <div class="col-2 text-center">
                        <h4>Step {{$stepOrder}}:</h4>
                    </div>
                    <div class="col">
                        {{$cookingStep->text}}
                    </div>
                </div>
            @php
                $stepOrder++
            @endphp
            @endforeach
        </div>
    </div>
</x-base>

resources/views/user/login.blade.php
<x-base>
    <section class="vh-100 bg-image"
             style="background-image: url({{asset('images/background_image/register-form.jpg')}});">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Log into your account</h2>

                                <form action="{{route('user.authenticate')}}" method="POST">
                                    @csrf
                                    <div class="form-outline mb-4">
                                        <input type="email" name="email" id="email" class="form-control form-control-lg" value="{{old('email')}}"/>
                                        <label class="form-label" for="email">Email</label>
                                        @error('email')
                                        <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" name="password" id="password" class="form-control form-control-lg" value="{{old('password')}}"/>
                                        <label class="form-label" for="password">Password</label>
                                        @error('password')
                                        <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="d-flex justify-content-center">
                                        <button class="btn btn-primary btn-block btn-lg gradient-custom-4">Log in</button>
                                    </div>

                                    <p class="text-center text-muted mt-5 mb-0">Don't have an account?
                                        <a href="{{route('register')}}" class="fw-bold text-body"><u>Register here</u></a>
                                    </p>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</x-base>

resources/views/user/register.blade.php
<x-base>
    <section class="vh-100 bg-image"
             style="background-image: url({{asset('images/background_image/register-form.jpg')}});">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Create an account</h2>

                                <form action="{{route('user.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-outline mb-4">
                                        <input type="text" name="username" id="username" class="form-control form-control-lg" value="{{old('username')}}" />
                                        <label class="form-label" for="username">Username</label>
                                        @error('username')
                                            <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="email" name="email" id="email" class="form-control form-control-lg" value="{{old('email')}}"/>
                                        <label class="form-label" for="email">Email</label>
                                        @error('email')
                                            <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" name="password" id="password" class="form-control form-control-lg" value="{{old('password')}}"/>
                                        <label class="form-label" for="password">Password</label>
                                        @error('password')
                                            <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control form-control-lg" value="{{old('password_confirmation')}}"/>
                                        <label class="form-label" for="password_confirmation">Repeat your password</label>
                                        @error('password_confirmation')
                                            <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="input-group mb-3">
                                        <input type="file" name="image" class="form-control" id="image">
                                        <label class="input-group-text" for="image">Upload</label>
                                        @error('image')
                                            <p class="text-danger">{{ $message }}</p>
                                        @enderror
                                    </div>

                                    <div class="d-flex justify-content-center">
                                        <button class="btn btn-primary btn-block btn-lg gradient-custom-4">Register</button>
                                    </div>

                                    <p class="text-center text-muted mt-5 mb-0">Have already an account?
                                        <a href="{{route('login')}}" class="fw-bold text-body"><u>Login here</u></a>
                                    </p>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</x-base>